### ISSUE TITLE
Issue with creation of environment using provided requirements.txt

### ISSUE THREAD

**Issue by ElisonSherton** [leebebeto/Inter-Prototype#6]
Hi!

I was trying to create an environment using the provided `requirements.txt` file in a python3.8 runtime and encountered the following error. Can someone please help on the resolution of the same?

```python
Collecting bcolz
  Using cached bcolz-1.2.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.7 in /home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages (from bcolz) (1.24.4)
Building wheels for collected packages: bcolz
  Building wheel for bcolz (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      /tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/setup.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import resource_filename
      /home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/arrayprint.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/__init__.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/toplevel.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/attrs.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/version.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/chunked_eval.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/py2help_tests.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/defaults.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/utils.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/ctable.py -> build/lib.linux-x86_64-cpython-38/bcolz
      copying bcolz/py2help.py -> build/lib.linux-x86_64-cpython-38/bcolz
      creating build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/all.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_carray.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/__init__.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_carray_objects.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_attrs.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_ndcarray.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_queries.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/common.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/tests/test_ctable.py -> build/lib.linux-x86_64-cpython-38/bcolz/tests
      copying bcolz/carray_ext.pxd -> build/lib.linux-x86_64-cpython-38/bcolz
      running build_ext
      Compiling bcolz/carray_ext.pyx because it changed.
      [1/1] Cythonizing bcolz/carray_ext.pyx
      /tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/.eggs/Cython-3.0.4-py3.8-linux-x86_64.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/bcolz/carray_ext.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # Create the final container and fill it
              out = carray([], dtype=newdtype, cparams=self.cparams,
                             expectedlen=newlen,
                             rootdir=rootdir, mode='w')
              if newlen < ilen:
                  rsize = isize / newlen
                                ^
      ------------------------------------------------------------
      
      bcolz/carray_ext.pyx:1685:26: Cannot assign type 'double' to 'npy_intp'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/setup.py", line 161, in <module>
          setup(
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/setup.py", line 77, in build_extensions
          cython_build_ext.build_extensions(self)
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/vinayak.n/anaconda3/envs/temp/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/.eggs/Cython-3.0.4-py3.8-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 130, in build_extension
          new_ext = cythonize(
        File "/tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/.eggs/Cython-3.0.4-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-install-fvclwh_4/bcolz_bdd3f0e6903044caab741dd8ede2207e/.eggs/Cython-3.0.4-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: bcolz/carray_ext.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bcolz
  Running setup.py clean for bcolz
Failed to build bcolz
ERROR: Could not build wheels for bcolz, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.
```

**Comment by ElisonSherton** [comment]
Solved this issue, found an alternate way of installing bcolz using [this package](https://pypi.org/project/bcolz-zipline/)
